# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Josh Pullin - Front End Web Developer
email: joshpullin134@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a front end web developer interested in responsive design and UI/UX, 
  because let's face it, no one wants to use an ugly, hard to nagivate site.
  Experienced in HTML5, CSS3, JavaScript (including jQuery), Python, and Ruby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "joshpullin.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
